$ grunt
Running "jshint:source" (jshint) task
>> 24 files lint free.

Running "jshint:tests" (jshint) task
>> 25 files lint free.

Running "jshint:grunt" (jshint) task
>> 1 file lint free.

Running "concat:dist" (concat) task
File dist/angular-leaflet-directive.pre.js created.

Running "ngAnnotate:dist" (ngAnnotate) task
>> 1 file successfully generated.

Running "uglify:dist" (uglify) task
>> 1 file created.

Running "karma:unit" (karma) task
INFO [karma]: Karma v0.12.23 server started at http://localhost:9018/
INFO [launcher]: Starting browser PhantomJS
connect: res.headerSent: use standard res.headersSent
INFO [PhantomJS 1.9.7 (Windows 7)]: Connected on socket NsAl4vm9SQZj3FYZUyNF with id 811947
PhantomJS 1.9.7 (Windows 7): Executed 55 of 140 SUCCESS (0 secs / 0.242 secs)
PhantomJS 1.9.7 (Windows 7): Executed 73 of 140 SUCCESS (0 secs / 0.462 secs)
WARN [web-server]: 404: /base/bower_components/leaflet/dist/images/marker-shadow.png
PhantomJS 1.9.7 (Windows 7): Executed 140 of 140 SUCCESS (2.693 secs / 2.844 secs)

Running "concat:license" (concat) task
File dist/angular-leaflet-directive.min.js created.

Done, without errors.
